Kekule.Localization.setCurrModule("general");

Kekule.Localization.addResource("zh", "Texts",
{
	"UNNAMED": "未命名"
});

Kekule.Localization.addResource("zh", "ErrorMsg",
{
	"MODULE_NOT_LOADED": "模块{0}未载入",
	"UNIT_NOT_FOUND": "Unit not found: {0}",
	"STANDARD_UNIT_OF_CATEGORY_NOT_FOUND": "类别{0}的标准单位未设置",
	"UNABLE_TO_CONVERT_BETWEEN_UNITS": "无法在单位{0}与{1}间转换数据",
	"NON_OWN_PROPERTY_CANNOT_BE_REPLACED": "只能替换对象的直接属性",
	"EMPTY_DOC": "文档无内容",
	"ELEMENT_NOTSET": "未设置元素",
	"EMPTY_RESURI": "资源URI无内容",
	"CANNOT_LOAD_RES_OF_URI": "无法载入资源URI：",
	"LIST_ITEM_CLASS_MISMATCH": "条目类型错误，无法加入列表",
	"CANNOT_CLEAR_WEAKMAP": "Can not clear a weak map",
	"CANNOT_GET_KEY_LIST_IN_WEAKMAP": "Can not get key array from a weak map",
	"CANNOT_GET_VALUE_LIST_IN_WEAKMAP": "Can not get value array from a weak map",
	"INVALID_CHEMELEMENT": "无效的化学元素",
	"INVALID_ISOTOPE": "无效的同位素",
	"COORD_STICK_NOT_ALLOWED_ON_CLASS": "Coordinate sticking is not allowed in this type of object",
	"INVALID_STICK_TARGET_OBJ": "Invalid sticking target",
	"UNABLE_TO_STICK_TO_OTHER_OWNER_OBJ": "Unable to stick to object with a different owner",
	"UNABLE_TO_STICK_TO_OBJ_WITHOUT_ABS_COORD": "Unable to stick to object without absolute coordinates",
	"STICK_RECURSION_NOT_ALLOWED": "Stick recursion is not allowed",
	"UNABLE_ADD_MISTYPED_NODE": "无法向键/连接符上连接错误的原子/顶点",
	"UNABLE_ADD_DIFF_OWNER_OBJ": "对象有着不同的宿主，无法连接在同一键/连接符上",
	"CHEMSTRUCTUREOBJECTGROUP_ITEMCLASS_MISMATCH": "条目类型不符",
	"SORT_FUNC_UNSET": "排序函数未设置",
	"SOURCE_FRAGMENT_NOT_SET": "未指定源分子",
	"UNABLE_ADD_NONMOLECULE_MAP": "仅能向反应物或生成物中添加分子",
	"CANNOT_ADD_NON_NODE_NOR_CONNECTOR_TO_STRUCT_CONTAINER": "仅能向结构中添加原子、键或顶点、连接符",
	"REGISTERED_CANONICALIZATION_EXECUTOR_NOT_FOUND": "无法找到注册的归一化执行器",
	"ERROR_LOADING_FILE": "文件载入错误：",
	"READER_ID_ALREADY_EXISTS": "Can not register reader: id already exists",
	"WRITER_ID_ALREADY_EXISTS": "Can not register writer: id already exists",
	"FAIL_TO_READ_FORMAT": "读入数据失败，格式：",
	"NO_SUITABLE_READER_FOR_FORMAT": "无法读入数据，格式：",
	"NO_SUITABLE_READER_FOR_MIMETYPE": "无法读入数据，MIME类型：",
	"NO_SUITABLE_READER_FOR_FILEEXT": "无法读入数据，文件后缀：",
	"NO_SUITABLE_WRITER_FOR_FORMAT": "无法写入数据，格式：",
	"NO_SUITABLE_WRITER_FOR_MIMETYPE": "无法写入数据，MIME类型：",
	"NO_SUITABLE_WRITER_FOR_FILEEXT": "无法写入数据，文件后缀：",
	"AJAX_FILELOADER_NOT_FOUND": "AJAX file loader not found, can not load URL",
	"FAIL_TO_LOAD_FILE_URL": "载入文件或链接失败：",
	"CML_ELEM_READER_NOT_FOUND": "CML元素<{0}>读入器不存在",
	"ATOMID_NOT_EXISTS": "原子标识(ID)不存在：",
	"BONDID_NOT_EXISTS": "键标识(ID)不存在：",
	"CML_ELEM_WRITER_TYPE_INPROPER": "{0}不是合适的CML元素{1}的写入器",
	"CML_CAN_NOT_OUTPUT_TO_EMPTY_ELEMENT": "无法向空的CML元素中输出内容",
	"UNABLE_TO_OUTPUT_AS_CML": "无法将对象<{0}>输出至CML",
	"MDL_CTAB_ATOM_CANNOT_CREATE": "无法从源MDL格式数据中创建原子",
	"MDL_CTAB_BOND_CANNOT_CREATE": "无法从源MDL格式数据中创建化学键",
	"CAN_NOT_WRITE_NON_MOLECULE_TO_MOL": "对象并非分子，无法输出至分子连接表",
	"MOLECULE_HAS_NO_CTAB_TO_OUTPUT": "分子无连接表，无法输出至MDL格式数据",
	"NOT_MDL2000_FORMAT_DATA": "数据格式错误：并非MDL 2000",
	"NOT_MDL_RXN_DATA": "并非MDL反应(RXN)数据",
	"MALFORMED_MDL3000_COUNTLINE": "MDL 3000计数行格式错误",
	"MDL3000_ATOMBLOCK_NOT_FOUND": "无法找到原子块，错误的MDL 3000数据？",
	"NOT_MDL_FORMAT_DATA": "数据格式错误：并非MDL 2000或3000",
	"NOT_MDL2000_RXN_DATA": "并非MDL RXN 2000数据",
	"NOT_MDL3000_RXN_DATA": "并非MDL RXN 3000数据",
	"NOT_MDL3000_RXN_COUNTLINE": "读入RXN 3000计数行错误",
	"MDL_OUTPUT_DATATYPE_NOT_TEXT": "MDL数据无法输出为非文本格式",
	"MDL_INPUT_DATATYPE_NOT_TEXT": "非文本格式数据，非法的MDL源数据",
	"UNABLE_TO_OUTPUT_AS_MDL": "无法将对象<{0}>输出至MDL格式数据",
	"KCJ_INPUT_DATATYPE_NOT_JSON_OR_TEXT": "非文本或JSON格式数据，非法的KCJ源数据",
	"KCJ_OUTPUT_DATATYPE_NOT_JSON_OR_TEXT": "无法输出为非文本或JSON格式",
	"KCX_INPUT_DATATYPE_NOT_DOM_OR_TEXT": "非文本或DOM格式数据，非法的KCX源数据",
	"KCX_OUTPUT_DATATYPE_NOT_DOM_OR_TEXT": "无法输出为非文本或DOM格式",
	"JSON_SERIALIZER_NOT_EXISTS": "JSON序列化器不存在",
	"XML_SERIALIZER_NOT_EXISTS": "XML序列化器不存在",
	"JCAMP_DATA_WITHOUT_TITLE_LINE": "不正确的JCAMP格式数据：TITLE标签缺失",
	"JCAMP_OTHER_LABEL_BEFORE_TITLE_LINE": "不正确的JCAMP格式数据：未以TITLE标签起始",
	"JCAMP_MORE_THAN_ONE_ROOT_BLOCK": "不正确的JCAMP格式数据：存在多个根数据块",
	"JCAMP_MORE_THAN_TWO_NEST_LEVEL": "不正确的JCAMP格式数据：超过两层数据块嵌套",
	"JCAMP_ASDF_FORMAT_ERROR_WITH_STR": "不正确的JCAMP ASDF字符串: {0}",
	"JCAMP_DATA_TABLE_X_VALUE_CHECK_ERROR": "JCAMP数据表X值校验失败!",
	"JCAMP_DATA_TABLE_Y_VALUE_CHECK_ERROR": "JCAMP数据表Y值校验失败!",
	"JCAMP_DATA_TABLE_VALUE_FIRST_LAST_NOT_MATCH": "JCAMP数据表起始/终止数据不匹配",
	"JCAMP_DATA_TABLE_VAR_LIST_FORMAT_ERROR": "Malformed JCAMP variable list format: {0}",
	"JCAMP_DATA_TABLE_VAR_LIST_FORMAT_UNSUPPORTED": "Unsupported JCAMP variable list format: {0}",
	"JCAMP_NTUPLES_BEGIN_END_NAME_NOT_MATCH": "Ntuples name not match in begin/end labels: {0} and {1}",
	"JCAMP_NTUPLES_PAGE_DECLARATION_FORMAT_ERROR": "Malformed JCAMP ntuples page declaration: {0}",
	"JCAMP_LDR_TARGET_UNIT_NOT_MATCH_WITH_DETAIL": "The unit of property {0} ({1}) can not be converted to the request one ({2}) for JCAMP {3} LDR",
	"FAILED_TO_ASSIGN_SYMBOL_TO_VARIABLE": "Fail to assign a symbol to variable {0}",
	"JCAMP_IMPLICIT_HYDROGEN_COUNT_NOT_MATCH_DETAIL": "Unmatched implicit hydrogen count for atom {0}({1}), expect {2} but found {3}",
	"VISIBLE_DATA_RANGE_IS_EMPTY": "The visible range of data is empty, unable to draw the spectrum",
	"INAVAILABLE_AUTOSCALE_REF_LENGTH": "无法计算自动缩放所需的长度",
	"FORMULA_RENDERER_3D_NOT_AVAILABLE": "分子式3D渲染器暂不可用",
	"CANNOT_FIND_SUITABLE_RENDERER_FOR_OBJ": "无法找到合适的渲染器",
	"THREEJS_LIB_NOT_UNAVAILABLE": "Three.js不可用，请使用<script>标签将其引入或使用Kekule.externalResourceManager.register方法指定Three实例",
	"THREEJS_DRAWING_NOT_UNAVAILABLE": "浏览器不支持Webgl、Canvas或SVG，请将其升级或更换",
	"CANVAS2D_NOT_UNAVAILABLE": "浏览器不支持Canvas，请将其升级或更换",
	"RAPHAEL_LIB_NOT_UNAVAILABLE": "Raphael.js不可用，请使用<script>标签将其引入",
	"RAPHAEL_SVG_VML_UNAVAILABLE": "浏览器不支持SVG或VML，请将其升级或更换。",
	"CALC_TERMINATED_BY_USER": "计算过程被用户中断",
	"CALC_SERVICE_UNAVAILABLE": "计算服务“{0}”不可用"
});

Kekule.Localization.addResource("zh", "ErrorCheckMsg",
{
	"GENERAL_ERROR_WITH_CODE": "错误代码: {0}",
	"ATOM_VALENCE_ERROR_WITH_SUGGEST": "{0}原子价数（{1}）异于常见值（{2}）",
	"ATOM_VALENCE_ERROR_WITH_SUGGESTS": "{0}原子价数（{1}）异于常见值（{2}）",
	"BOND_ORDER_EXCEED_ALLOWED_WITH_SUGGEST": "共价键键级（{0}）超出允许值（{1}）范围",
	"BOND_WITH_ID_ORDER_EXCEED_ALLOWED_WITH_SUGGEST": "{0}键键级（{1}）超出允许值（{2}）范围",
	"NODE_DISTANCE_TOO_CLOSE": "原子或基团位置过于接近",
	"NODE_DISTANCE_TOO_CLOSE_WITH_LABEL": "原子或基团（{0}）位置过于接近",
	"TITLE_CHANGE_BOND_ORDER_TO": "将键级修改为{0}",
	"DESCRIPTION_CHANGE_BOND_ORDER_TO": "将键级由{0}修改为{1}",
	"TITLE_MERGE_TO": "将{0}与{1}合并",
	"DESCRIPTION_MERGE_TO": "将节点{0}与{1}合并"
});

