Kekule.Localization.setCurrModule("general");

Kekule.Localization.addResource("zh", "Texts",
		{
			"UNNAMED": "未命名"
		});

Kekule.Localization.addResource("zh", "ErrorMsg",
		{
			"MODULE_NOT_LOADED": "模块{0}未载入",
			"NON_OWN_PROPERTY_CANNOT_BE_REPLACED": "只能替换对象的直接属性",
			"EMPTY_DOC": "文档无内容",
			"ELEMENT_NOTSET": "未设置元素",
			"EMPTY_RESURI": "资源URI无内容",
			"CANNOT_LOAD_RES_OF_URI": "无法载入资源URI：",
			"LIST_ITEM_CLASS_MISMATCH": "条目类型错误，无法加入列表",
			"CANNOT_CLEAR_WEAKMAP": "Can not clear a weak map",
			"CANNOT_GET_KEY_LIST_IN_WEAKMAP": "Can not get key array from a weak map",
			"CANNOT_GET_VALUE_LIST_IN_WEAKMAP": "Can not get value array from a weak map",
			"INVALID_CHEMELEMENT": "无效的化学元素",
			"INVALID_ISOTOPE": "无效的同位素",
			"UNABLE_ADD_MISTYPED_NODE": "无法向键/连接符上连接错误的原子/顶点",
			"UNABLE_ADD_DIFF_OWNER_OBJ": "对象有着不同的宿主，无法连接在同一键/连接符上",
			"CHEMSTRUCTUREOBJECTGROUP_ITEMCLASS_MISMATCH": "条目类型不符",
			"SORT_FUNC_UNSET": "排序函数未设置",
			"SOURCE_FRAGMENT_NOT_SET": "未指定源分子",
			"UNABLE_ADD_NONMOLECULE_MAP": "仅能向反应物或生成物中添加分子",
			"CANNOT_ADD_NON_NODE_NOR_CONNECTOR_TO_STRUCT_CONTAINER": "仅能向结构中添加原子、键或顶点、连接符",
			"REGISTERED_CANONICALIZATION_EXECUTOR_NOT_FOUND": "无法找到注册的归一化执行器",
			"ERROR_LOADING_FILE": "文件载入错误：",
			"READER_ID_ALREADY_EXISTS": "Can not register reader: id already exists",
			"WRITER_ID_ALREADY_EXISTS": "Can not register writer: id already exists",
			"FAIL_TO_READ_FORMAT": "读入数据失败，格式：",
			"NO_SUITABLE_READER_FOR_FORMAT": "无法读入数据，格式：",
			"NO_SUITABLE_READER_FOR_MIMETYPE": "无法读入数据，MIME类型：",
			"NO_SUITABLE_READER_FOR_FILEEXT": "无法读入数据，文件后缀：",
			"NO_SUITABLE_WRITER_FOR_FORMAT": "无法写入数据，格式：",
			"NO_SUITABLE_WRITER_FOR_MIMETYPE": "无法写入数据，MIME类型：",
			"NO_SUITABLE_WRITER_FOR_FILEEXT": "无法写入数据，文件后缀：",
			"AJAX_FILELOADER_NOT_FOUND": "AJAX file loader not found, can not load URL",
			"FAIL_TO_LOAD_FILE_URL": "载入文件或链接失败：",
			"CML_ELEM_READER_NOT_FOUND": "CML元素<{0}>读入器不存在",
			"ATOMID_NOT_EXISTS": "原子标识(ID)不存在：",
			"BONDID_NOT_EXISTS": "键标识(ID)不存在：",
			"CML_ELEM_WRITER_TYPE_INPROPER": "{0}不是合适的CML元素{1}的写入器",
			"CML_CAN_NOT_OUTPUT_TO_EMPTY_ELEMENT": "无法向空的CML元素中输出内容",
			"UNABLE_TO_OUTPUT_AS_CML": "无法将对象<{0}>输出至CML",
			"MDL_CTAB_ATOM_CANNOT_CREATE": "无法从源MDL格式数据中创建原子",
			"MDL_CTAB_BOND_CANNOT_CREATE": "无法从源MDL格式数据中创建化学键",
			"CAN_NOT_WRITE_NON_MOLECULE_TO_MOL": "对象并非分子，无法输出至分子连接表",
			"MOLECULE_HAS_NO_CTAB_TO_OUTPUT": "分子无连接表，无法输出至MDL格式数据",
			"NOT_MDL2000_FORMAT_DATA": "数据格式错误：并非MDL 2000",
			"NOT_MDL_RXN_DATA": "并非MDL反应(RXN)数据",
			"MALFORMED_MDL3000_COUNTLINE": "MDL 3000计数行格式错误",
			"MDL3000_ATOMBLOCK_NOT_FOUND": "无法找到原子块，错误的MDL 3000数据？",
			"NOT_MDL_FORMAT_DATA": "数据格式错误：并非MDL 2000或3000",
			"NOT_MDL2000_RXN_DATA": "并非MDL RXN 2000数据",
			"NOT_MDL3000_RXN_DATA": "并非MDL RXN 3000数据",
			"NOT_MDL3000_RXN_COUNTLINE": "读入RXN 3000计数行错误",
			"MDL_OUTPUT_DATATYPE_NOT_TEXT": "MDL数据无法输出为非文本格式",
			"MDL_INPUT_DATATYPE_NOT_TEXT": "非文本格式数据，非法的MDL源数据",
			"UNABLE_TO_OUTPUT_AS_MDL": "无法将对象<{0}>输出至MDL格式数据",
			"KCJ_INPUT_DATATYPE_NOT_JSON_OR_TEXT": "非文本或JSON格式数据，非法的KCJ源数据",
			"KCJ_OUTPUT_DATATYPE_NOT_JSON_OR_TEXT": "无法输出为非文本或JSON格式",
			"KCX_INPUT_DATATYPE_NOT_DOM_OR_TEXT": "非文本或DOM格式数据，非法的KCX源数据",
			"KCX_OUTPUT_DATATYPE_NOT_DOM_OR_TEXT": "无法输出为非文本或DOM格式",
			"JSON_SERIALIZER_NOT_EXISTS": "JSON序列化器不存在",
			"XML_SERIALIZER_NOT_EXISTS": "XML序列化器不存在",
			"INAVAILABLE_AUTOSCALE_REF_LENGTH": "无法计算自动缩放所需的长度",
			"FORMULA_RENDERER_3D_NOT_AVAILABLE": "分子式3D渲染器暂不可用",
			"CANNOT_FIND_SUITABLE_RENDERER_FOR_OBJ": "无法找到合适的渲染器",
			"CALC_TERMINATED_BY_USER": "计算过程被用户中断",
			"CALC_SERVICE_UNAVAILABLE": "计算服务“{0}”不可用"
		});

