ID example_sw chemdig rzepa  GRAA_HUMAN     STANDARD;      PRT;   262 AA.
AC   P12544;
DT   01-OCT-1989 (REL. 12, CREATED) chemdig rzepa
DT   01-OCT-1989 (REL. 12, LAST SEQUENCE UPDATE)
DT   15-DEC-1998 (REL. 37, LAST ANNOTATION UPDATE)
DE   GRANZYME A PRECURSOR (EC 3.4.21.78) (CYTOTOXIC T-LYMPHOCYTE PROTEINASE
DE   1) (HANUKKAH FACTOR) (H FACTOR) (HF) (GRANZYME 1) (CTL TRYPTASE)
DE   (FRAGMENTIN 1).
GN   GZMA OR CTLA3 OR HFSP.
OS   HOMO SAPIENS (HUMAN).
OC   Eukaryota; Metazoa; Chordata; Vertebrata; Mammalia; Eutheria;
OC   Primates; Catarrhini; Hominidae; Homo.
RN   [1]
RP   SEQUENCE FROM N.A.
RC   TISSUE=T-CELL;
RX   MEDLINE; 88125000.
RA   GERSHENFELD H.K., HERSHBERGER R.J., SHOWS T.B., WEISSMAN I.L.;
RT   "Cloning and chromosomal assignment of a human cDNA encoding a T
RT   cell- and natural killer cell-specific trypsin-like serine
RT   protease.";
RL   PROC. NATL. ACAD. SCI. U.S.A. 85:1184-1188(1988).
RN   [2]
RP   SEQUENCE OF 29-53.
RX   MEDLINE; 88330824.
RA   POE M., BENNETT C.D., BIDDISON W.E., BLAKE J.T., NORTON G.P.,
RA   RODKEY J.A., SIGAL N.H., TURNER R.V., WU J.K., ZWEERINK H.J.;
RT   "Human cytotoxic lymphocyte tryptase. Its purification from granules
RT   and the characterization of inhibitor and substrate specificity.";
RL   J. BIOL. CHEM. 263:13215-13222(1988).
RN   [3]
RP   SEQUENCE OF 29-40, AND CHARACTERIZATION.
RX   MEDLINE; 89009866.
RA   HAMEED A., LOWREY D.M., LICHTENHELD M., PODACK E.R.;
RT   "Characterization of three serine esterases isolated from human IL-2
RT   activated killer cells.";
RL   J. IMMUNOL. 141:3142-3147(1988).
RN   [4]
RP   SEQUENCE OF 29-39, AND CHARACTERIZATION.
RX   MEDLINE; 89035468.
RA   KRAEHENBUHL O., REY C., JENNE D.E., LANZAVECCHIA A., GROSCURTH P.,
RA   CARREL S., TSCHOPP J.;
RT   "Characterization of granzymes A and B isolated from granules of
RT   cloned human cytotoxic T lymphocytes.";
RL   J. IMMUNOL. 141:3471-3477(1988).
RN   [5]
RP   3D-STRUCTURE MODELLING.
RX   MEDLINE; 89184501.
RA   MURPHY M.E.P., MOULT J., BLEACKLEY R.C., GERSHENFELD H.,
RA   WEISSMAN I.L., JAMES M.N.G.;
RT   "Comparative molecular model building of two serine proteinases from
RT   cytotoxic T lymphocytes.";
RL   PROTEINS 4:190-204(1988).
CC   -!- FUNCTION: THIS ENZYME IS NECESSARY FOR TARGET CELL LYSIS IN CELL-
CC       MEDIATED IMMUNE RESPONSES. IT CLEAVES AFTER LYS OR ARG. MAY BE
CC       INVOLVED IN APOPTOSIS.
CC   -!- CATALYTIC ACTIVITY: HYDROLYSIS OF PROTEINS, INCLUDING FIBRONECTIN,
CC       TYPE IV COLLAGEN AND NUCLEOLIN. PREFERENTIAL CLEAVAGE: ARG-|-XAA,
CC       LYS-|-XAA >> PHE-|-XAA IN SMALL MOLECULE SUBSTRATES.
CC   -!- SUBUNIT: HOMODIMER, DISULFIDE-LINKED.
CC   -!- SUBCELLULAR LOCATION: CYTOPLASMIC GRANULES.
CC   -!- SIMILARITY: BELONGS TO PEPTIDASE FAMILY S1; ALSO KNOWN AS THE
CC       TRYPSIN FAMILY. STRONGEST TO OTHER GRANZYMES AND TO MAST CELL
CC       PROTEASES.
DR   EMBL; M18737; G306845; -.
DR   PIR; A28943; A28943.
DR   PIR; A30525; A30525.
DR   PIR; A30526; A30526.
DR   PIR; A31372; A31372.
DR   PDB; 1HF1; 15-OCT-94.
DR   MIM; 140050; -.
DR   PROSITE; PS00134; TRYPSIN_HIS; 1.
DR   PROSITE; PS00135; TRYPSIN_SER; 1.
DR   PFAM; PF00089; trypsin; 1.
KW   HYDROLASE; SERINE PROTEASE; ZYMOGEN; SIGNAL; T-CELL; CYTOLYSIS;
KW   APOPTOSIS; 3D-STRUCTURE.
FT   SIGNAL        1     26
FT   PROPEP       27     28       ACTIVATION PEPTIDE.
FT   CHAIN        29    262       GRANZYME A.
FT   ACT_SITE     69     69       CHARGE RELAY SYSTEM (BY SIMILARITY).
FT   ACT_SITE    114    114       CHARGE RELAY SYSTEM (BY SIMILARITY).
FT   ACT_SITE    212    212       CHARGE RELAY SYSTEM (BY SIMILARITY).
FT   DISULFID     54     70       BY SIMILARITY.
FT   DISULFID    148    218       BY SIMILARITY.
FT   DISULFID    179    197       BY SIMILARITY.
FT   DISULFID    208    234       BY SIMILARITY.
FT   CARBOHYD    170    170       POTENTIAL.
SQ   SEQUENCE   262 AA;  28968 MW;  34E965D7 CRC32;
     MRNSYRFLAS SLSVVVSLLL IPEDVCEKII GGNEVTPHSR PYMVLLSLDR KTICAGALIA
     KDWVLTAAHC NLNKRSQVIL GAHSITREEP TKQIMLVKKE FPYPCYDPAT REGDLKLLQL
     TEKAKINKYV TILHLPKKGD DVKPGTMCQV AGWGRTHNSA SWSDTLREVN ITIIDRKVCN
     DRNHYNFNPV IGMNMVCAGS LRGGRDSCNG DSGSPLLCEG VFRGVTSFGL ENKCGDPRGP
     GVYILLSKKH LNWIIMTIKG AV
//

